CREATE TABLE IF NOT EXISTS todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL,
  due TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS user_session (id BLOB PRIMARY KEY, data BLOB NOT NULL);
